/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class StandardisedFields extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StandardisedFields\",\"namespace\":\"com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields\",\"fields\":[{\"name\":\"COMPANY_NAME\",\"type\":[\"null\",\"string\"],\"default\":null,\"dataClassification\":\"3\"},{\"name\":\"PROCESSING_DATE\",\"type\":[\"null\",\"string\"],\"default\":null,\"dataClassification\":\"3\"},{\"name\":\"ADDRESS_HOUSE_NUMBER\",\"type\":[\"null\",\"string\"],\"default\":null,\"dataClassification\":\"3\"},{\"name\":\"ADDRESS_STREET\",\"type\":[\"null\",\"string\"],\"default\":null,\"dataClassification\":\"3\"},{\"name\":\"ADDRESS_AREA\",\"type\":[\"null\",\"string\"],\"default\":null,\"dataClassification\":\"3\"},{\"name\":\"ADDRESS_POST_TOWN\",\"type\":[\"null\",\"string\"],\"default\":null,\"dataClassification\":\"3\"},{\"name\":\"ADDRESS_REGION\",\"type\":[\"null\",\"string\"],\"default\":null,\"dataClassification\":\"3\"},{\"name\":\"ADDRESS_COUNTRY\",\"type\":[\"null\",\"string\"],\"default\":null,\"dataClassification\":\"3\"},{\"name\":\"ADDRESS_POSTCODE\",\"type\":[\"null\",\"string\"],\"default\":null,\"dataClassification\":\"3\"},{\"name\":\"ADDRESS_CARE_OF\",\"type\":[\"null\",\"string\"],\"default\":null,\"dataClassification\":\"3\"},{\"name\":\"ADDRESS_SUPPLIED_COMPANY_NAME\",\"type\":[\"null\",\"string\"],\"default\":null,\"dataClassification\":\"3\"},{\"name\":\"ADDRESS_PO_BOX\",\"type\":[\"null\",\"string\"],\"default\":null,\"dataClassification\":\"3\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence COMPANY_NAME;
  @Deprecated public java.lang.CharSequence PROCESSING_DATE;
  @Deprecated public java.lang.CharSequence ADDRESS_HOUSE_NUMBER;
  @Deprecated public java.lang.CharSequence ADDRESS_STREET;
  @Deprecated public java.lang.CharSequence ADDRESS_AREA;
  @Deprecated public java.lang.CharSequence ADDRESS_POST_TOWN;
  @Deprecated public java.lang.CharSequence ADDRESS_REGION;
  @Deprecated public java.lang.CharSequence ADDRESS_COUNTRY;
  @Deprecated public java.lang.CharSequence ADDRESS_POSTCODE;
  @Deprecated public java.lang.CharSequence ADDRESS_CARE_OF;
  @Deprecated public java.lang.CharSequence ADDRESS_SUPPLIED_COMPANY_NAME;
  @Deprecated public java.lang.CharSequence ADDRESS_PO_BOX;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public StandardisedFields() {}

  /**
   * All-args constructor.
   */
  public StandardisedFields(java.lang.CharSequence COMPANY_NAME, java.lang.CharSequence PROCESSING_DATE, java.lang.CharSequence ADDRESS_HOUSE_NUMBER, java.lang.CharSequence ADDRESS_STREET, java.lang.CharSequence ADDRESS_AREA, java.lang.CharSequence ADDRESS_POST_TOWN, java.lang.CharSequence ADDRESS_REGION, java.lang.CharSequence ADDRESS_COUNTRY, java.lang.CharSequence ADDRESS_POSTCODE, java.lang.CharSequence ADDRESS_CARE_OF, java.lang.CharSequence ADDRESS_SUPPLIED_COMPANY_NAME, java.lang.CharSequence ADDRESS_PO_BOX) {
    this.COMPANY_NAME = COMPANY_NAME;
    this.PROCESSING_DATE = PROCESSING_DATE;
    this.ADDRESS_HOUSE_NUMBER = ADDRESS_HOUSE_NUMBER;
    this.ADDRESS_STREET = ADDRESS_STREET;
    this.ADDRESS_AREA = ADDRESS_AREA;
    this.ADDRESS_POST_TOWN = ADDRESS_POST_TOWN;
    this.ADDRESS_REGION = ADDRESS_REGION;
    this.ADDRESS_COUNTRY = ADDRESS_COUNTRY;
    this.ADDRESS_POSTCODE = ADDRESS_POSTCODE;
    this.ADDRESS_CARE_OF = ADDRESS_CARE_OF;
    this.ADDRESS_SUPPLIED_COMPANY_NAME = ADDRESS_SUPPLIED_COMPANY_NAME;
    this.ADDRESS_PO_BOX = ADDRESS_PO_BOX;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return COMPANY_NAME;
    case 1: return PROCESSING_DATE;
    case 2: return ADDRESS_HOUSE_NUMBER;
    case 3: return ADDRESS_STREET;
    case 4: return ADDRESS_AREA;
    case 5: return ADDRESS_POST_TOWN;
    case 6: return ADDRESS_REGION;
    case 7: return ADDRESS_COUNTRY;
    case 8: return ADDRESS_POSTCODE;
    case 9: return ADDRESS_CARE_OF;
    case 10: return ADDRESS_SUPPLIED_COMPANY_NAME;
    case 11: return ADDRESS_PO_BOX;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: COMPANY_NAME = (java.lang.CharSequence)value$; break;
    case 1: PROCESSING_DATE = (java.lang.CharSequence)value$; break;
    case 2: ADDRESS_HOUSE_NUMBER = (java.lang.CharSequence)value$; break;
    case 3: ADDRESS_STREET = (java.lang.CharSequence)value$; break;
    case 4: ADDRESS_AREA = (java.lang.CharSequence)value$; break;
    case 5: ADDRESS_POST_TOWN = (java.lang.CharSequence)value$; break;
    case 6: ADDRESS_REGION = (java.lang.CharSequence)value$; break;
    case 7: ADDRESS_COUNTRY = (java.lang.CharSequence)value$; break;
    case 8: ADDRESS_POSTCODE = (java.lang.CharSequence)value$; break;
    case 9: ADDRESS_CARE_OF = (java.lang.CharSequence)value$; break;
    case 10: ADDRESS_SUPPLIED_COMPANY_NAME = (java.lang.CharSequence)value$; break;
    case 11: ADDRESS_PO_BOX = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'COMPANY_NAME' field.
   */
  public java.lang.CharSequence getCOMPANYNAME() {
    return COMPANY_NAME;
  }

  /**
   * Sets the value of the 'COMPANY_NAME' field.
   * @param value the value to set.
   */
  public void setCOMPANYNAME(java.lang.CharSequence value) {
    this.COMPANY_NAME = value;
  }

  /**
   * Gets the value of the 'PROCESSING_DATE' field.
   */
  public java.lang.CharSequence getPROCESSINGDATE() {
    return PROCESSING_DATE;
  }

  /**
   * Sets the value of the 'PROCESSING_DATE' field.
   * @param value the value to set.
   */
  public void setPROCESSINGDATE(java.lang.CharSequence value) {
    this.PROCESSING_DATE = value;
  }

  /**
   * Gets the value of the 'ADDRESS_HOUSE_NUMBER' field.
   */
  public java.lang.CharSequence getADDRESSHOUSENUMBER() {
    return ADDRESS_HOUSE_NUMBER;
  }

  /**
   * Sets the value of the 'ADDRESS_HOUSE_NUMBER' field.
   * @param value the value to set.
   */
  public void setADDRESSHOUSENUMBER(java.lang.CharSequence value) {
    this.ADDRESS_HOUSE_NUMBER = value;
  }

  /**
   * Gets the value of the 'ADDRESS_STREET' field.
   */
  public java.lang.CharSequence getADDRESSSTREET() {
    return ADDRESS_STREET;
  }

  /**
   * Sets the value of the 'ADDRESS_STREET' field.
   * @param value the value to set.
   */
  public void setADDRESSSTREET(java.lang.CharSequence value) {
    this.ADDRESS_STREET = value;
  }

  /**
   * Gets the value of the 'ADDRESS_AREA' field.
   */
  public java.lang.CharSequence getADDRESSAREA() {
    return ADDRESS_AREA;
  }

  /**
   * Sets the value of the 'ADDRESS_AREA' field.
   * @param value the value to set.
   */
  public void setADDRESSAREA(java.lang.CharSequence value) {
    this.ADDRESS_AREA = value;
  }

  /**
   * Gets the value of the 'ADDRESS_POST_TOWN' field.
   */
  public java.lang.CharSequence getADDRESSPOSTTOWN() {
    return ADDRESS_POST_TOWN;
  }

  /**
   * Sets the value of the 'ADDRESS_POST_TOWN' field.
   * @param value the value to set.
   */
  public void setADDRESSPOSTTOWN(java.lang.CharSequence value) {
    this.ADDRESS_POST_TOWN = value;
  }

  /**
   * Gets the value of the 'ADDRESS_REGION' field.
   */
  public java.lang.CharSequence getADDRESSREGION() {
    return ADDRESS_REGION;
  }

  /**
   * Sets the value of the 'ADDRESS_REGION' field.
   * @param value the value to set.
   */
  public void setADDRESSREGION(java.lang.CharSequence value) {
    this.ADDRESS_REGION = value;
  }

  /**
   * Gets the value of the 'ADDRESS_COUNTRY' field.
   */
  public java.lang.CharSequence getADDRESSCOUNTRY() {
    return ADDRESS_COUNTRY;
  }

  /**
   * Sets the value of the 'ADDRESS_COUNTRY' field.
   * @param value the value to set.
   */
  public void setADDRESSCOUNTRY(java.lang.CharSequence value) {
    this.ADDRESS_COUNTRY = value;
  }

  /**
   * Gets the value of the 'ADDRESS_POSTCODE' field.
   */
  public java.lang.CharSequence getADDRESSPOSTCODE() {
    return ADDRESS_POSTCODE;
  }

  /**
   * Sets the value of the 'ADDRESS_POSTCODE' field.
   * @param value the value to set.
   */
  public void setADDRESSPOSTCODE(java.lang.CharSequence value) {
    this.ADDRESS_POSTCODE = value;
  }

  /**
   * Gets the value of the 'ADDRESS_CARE_OF' field.
   */
  public java.lang.CharSequence getADDRESSCAREOF() {
    return ADDRESS_CARE_OF;
  }

  /**
   * Sets the value of the 'ADDRESS_CARE_OF' field.
   * @param value the value to set.
   */
  public void setADDRESSCAREOF(java.lang.CharSequence value) {
    this.ADDRESS_CARE_OF = value;
  }

  /**
   * Gets the value of the 'ADDRESS_SUPPLIED_COMPANY_NAME' field.
   */
  public java.lang.CharSequence getADDRESSSUPPLIEDCOMPANYNAME() {
    return ADDRESS_SUPPLIED_COMPANY_NAME;
  }

  /**
   * Sets the value of the 'ADDRESS_SUPPLIED_COMPANY_NAME' field.
   * @param value the value to set.
   */
  public void setADDRESSSUPPLIEDCOMPANYNAME(java.lang.CharSequence value) {
    this.ADDRESS_SUPPLIED_COMPANY_NAME = value;
  }

  /**
   * Gets the value of the 'ADDRESS_PO_BOX' field.
   */
  public java.lang.CharSequence getADDRESSPOBOX() {
    return ADDRESS_PO_BOX;
  }

  /**
   * Sets the value of the 'ADDRESS_PO_BOX' field.
   * @param value the value to set.
   */
  public void setADDRESSPOBOX(java.lang.CharSequence value) {
    this.ADDRESS_PO_BOX = value;
  }

  /** Creates a new StandardisedFields RecordBuilder */
  public static com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder newBuilder() {
    return new com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder();
  }
  
  /** Creates a new StandardisedFields RecordBuilder by copying an existing Builder */
  public static com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder newBuilder(com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder other) {
    return new com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder(other);
  }
  
  /** Creates a new StandardisedFields RecordBuilder by copying an existing StandardisedFields instance */
  public static com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder newBuilder(com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields other) {
    return new com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder(other);
  }
  
  /**
   * RecordBuilder for StandardisedFields instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StandardisedFields>
    implements org.apache.avro.data.RecordBuilder<StandardisedFields> {

    private java.lang.CharSequence COMPANY_NAME;
    private java.lang.CharSequence PROCESSING_DATE;
    private java.lang.CharSequence ADDRESS_HOUSE_NUMBER;
    private java.lang.CharSequence ADDRESS_STREET;
    private java.lang.CharSequence ADDRESS_AREA;
    private java.lang.CharSequence ADDRESS_POST_TOWN;
    private java.lang.CharSequence ADDRESS_REGION;
    private java.lang.CharSequence ADDRESS_COUNTRY;
    private java.lang.CharSequence ADDRESS_POSTCODE;
    private java.lang.CharSequence ADDRESS_CARE_OF;
    private java.lang.CharSequence ADDRESS_SUPPLIED_COMPANY_NAME;
    private java.lang.CharSequence ADDRESS_PO_BOX;

    /** Creates a new Builder */
    private Builder() {
      super(com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.COMPANY_NAME)) {
        this.COMPANY_NAME = data().deepCopy(fields()[0].schema(), other.COMPANY_NAME);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.PROCESSING_DATE)) {
        this.PROCESSING_DATE = data().deepCopy(fields()[1].schema(), other.PROCESSING_DATE);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ADDRESS_HOUSE_NUMBER)) {
        this.ADDRESS_HOUSE_NUMBER = data().deepCopy(fields()[2].schema(), other.ADDRESS_HOUSE_NUMBER);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ADDRESS_STREET)) {
        this.ADDRESS_STREET = data().deepCopy(fields()[3].schema(), other.ADDRESS_STREET);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.ADDRESS_AREA)) {
        this.ADDRESS_AREA = data().deepCopy(fields()[4].schema(), other.ADDRESS_AREA);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.ADDRESS_POST_TOWN)) {
        this.ADDRESS_POST_TOWN = data().deepCopy(fields()[5].schema(), other.ADDRESS_POST_TOWN);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.ADDRESS_REGION)) {
        this.ADDRESS_REGION = data().deepCopy(fields()[6].schema(), other.ADDRESS_REGION);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.ADDRESS_COUNTRY)) {
        this.ADDRESS_COUNTRY = data().deepCopy(fields()[7].schema(), other.ADDRESS_COUNTRY);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.ADDRESS_POSTCODE)) {
        this.ADDRESS_POSTCODE = data().deepCopy(fields()[8].schema(), other.ADDRESS_POSTCODE);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.ADDRESS_CARE_OF)) {
        this.ADDRESS_CARE_OF = data().deepCopy(fields()[9].schema(), other.ADDRESS_CARE_OF);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.ADDRESS_SUPPLIED_COMPANY_NAME)) {
        this.ADDRESS_SUPPLIED_COMPANY_NAME = data().deepCopy(fields()[10].schema(), other.ADDRESS_SUPPLIED_COMPANY_NAME);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.ADDRESS_PO_BOX)) {
        this.ADDRESS_PO_BOX = data().deepCopy(fields()[11].schema(), other.ADDRESS_PO_BOX);
        fieldSetFlags()[11] = true;
      }
    }
    
    /** Creates a Builder by copying an existing StandardisedFields instance */
    private Builder(com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields other) {
            super(com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.SCHEMA$);
      if (isValidValue(fields()[0], other.COMPANY_NAME)) {
        this.COMPANY_NAME = data().deepCopy(fields()[0].schema(), other.COMPANY_NAME);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.PROCESSING_DATE)) {
        this.PROCESSING_DATE = data().deepCopy(fields()[1].schema(), other.PROCESSING_DATE);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ADDRESS_HOUSE_NUMBER)) {
        this.ADDRESS_HOUSE_NUMBER = data().deepCopy(fields()[2].schema(), other.ADDRESS_HOUSE_NUMBER);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ADDRESS_STREET)) {
        this.ADDRESS_STREET = data().deepCopy(fields()[3].schema(), other.ADDRESS_STREET);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.ADDRESS_AREA)) {
        this.ADDRESS_AREA = data().deepCopy(fields()[4].schema(), other.ADDRESS_AREA);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.ADDRESS_POST_TOWN)) {
        this.ADDRESS_POST_TOWN = data().deepCopy(fields()[5].schema(), other.ADDRESS_POST_TOWN);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.ADDRESS_REGION)) {
        this.ADDRESS_REGION = data().deepCopy(fields()[6].schema(), other.ADDRESS_REGION);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.ADDRESS_COUNTRY)) {
        this.ADDRESS_COUNTRY = data().deepCopy(fields()[7].schema(), other.ADDRESS_COUNTRY);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.ADDRESS_POSTCODE)) {
        this.ADDRESS_POSTCODE = data().deepCopy(fields()[8].schema(), other.ADDRESS_POSTCODE);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.ADDRESS_CARE_OF)) {
        this.ADDRESS_CARE_OF = data().deepCopy(fields()[9].schema(), other.ADDRESS_CARE_OF);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.ADDRESS_SUPPLIED_COMPANY_NAME)) {
        this.ADDRESS_SUPPLIED_COMPANY_NAME = data().deepCopy(fields()[10].schema(), other.ADDRESS_SUPPLIED_COMPANY_NAME);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.ADDRESS_PO_BOX)) {
        this.ADDRESS_PO_BOX = data().deepCopy(fields()[11].schema(), other.ADDRESS_PO_BOX);
        fieldSetFlags()[11] = true;
      }
    }

    /** Gets the value of the 'COMPANY_NAME' field */
    public java.lang.CharSequence getCOMPANYNAME() {
      return COMPANY_NAME;
    }
    
    /** Sets the value of the 'COMPANY_NAME' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder setCOMPANYNAME(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.COMPANY_NAME = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'COMPANY_NAME' field has been set */
    public boolean hasCOMPANYNAME() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'COMPANY_NAME' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder clearCOMPANYNAME() {
      COMPANY_NAME = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'PROCESSING_DATE' field */
    public java.lang.CharSequence getPROCESSINGDATE() {
      return PROCESSING_DATE;
    }
    
    /** Sets the value of the 'PROCESSING_DATE' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder setPROCESSINGDATE(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.PROCESSING_DATE = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'PROCESSING_DATE' field has been set */
    public boolean hasPROCESSINGDATE() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'PROCESSING_DATE' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder clearPROCESSINGDATE() {
      PROCESSING_DATE = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'ADDRESS_HOUSE_NUMBER' field */
    public java.lang.CharSequence getADDRESSHOUSENUMBER() {
      return ADDRESS_HOUSE_NUMBER;
    }
    
    /** Sets the value of the 'ADDRESS_HOUSE_NUMBER' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder setADDRESSHOUSENUMBER(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.ADDRESS_HOUSE_NUMBER = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'ADDRESS_HOUSE_NUMBER' field has been set */
    public boolean hasADDRESSHOUSENUMBER() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'ADDRESS_HOUSE_NUMBER' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder clearADDRESSHOUSENUMBER() {
      ADDRESS_HOUSE_NUMBER = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'ADDRESS_STREET' field */
    public java.lang.CharSequence getADDRESSSTREET() {
      return ADDRESS_STREET;
    }
    
    /** Sets the value of the 'ADDRESS_STREET' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder setADDRESSSTREET(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.ADDRESS_STREET = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'ADDRESS_STREET' field has been set */
    public boolean hasADDRESSSTREET() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'ADDRESS_STREET' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder clearADDRESSSTREET() {
      ADDRESS_STREET = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'ADDRESS_AREA' field */
    public java.lang.CharSequence getADDRESSAREA() {
      return ADDRESS_AREA;
    }
    
    /** Sets the value of the 'ADDRESS_AREA' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder setADDRESSAREA(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.ADDRESS_AREA = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'ADDRESS_AREA' field has been set */
    public boolean hasADDRESSAREA() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'ADDRESS_AREA' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder clearADDRESSAREA() {
      ADDRESS_AREA = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'ADDRESS_POST_TOWN' field */
    public java.lang.CharSequence getADDRESSPOSTTOWN() {
      return ADDRESS_POST_TOWN;
    }
    
    /** Sets the value of the 'ADDRESS_POST_TOWN' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder setADDRESSPOSTTOWN(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.ADDRESS_POST_TOWN = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'ADDRESS_POST_TOWN' field has been set */
    public boolean hasADDRESSPOSTTOWN() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'ADDRESS_POST_TOWN' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder clearADDRESSPOSTTOWN() {
      ADDRESS_POST_TOWN = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'ADDRESS_REGION' field */
    public java.lang.CharSequence getADDRESSREGION() {
      return ADDRESS_REGION;
    }
    
    /** Sets the value of the 'ADDRESS_REGION' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder setADDRESSREGION(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.ADDRESS_REGION = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'ADDRESS_REGION' field has been set */
    public boolean hasADDRESSREGION() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'ADDRESS_REGION' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder clearADDRESSREGION() {
      ADDRESS_REGION = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'ADDRESS_COUNTRY' field */
    public java.lang.CharSequence getADDRESSCOUNTRY() {
      return ADDRESS_COUNTRY;
    }
    
    /** Sets the value of the 'ADDRESS_COUNTRY' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder setADDRESSCOUNTRY(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.ADDRESS_COUNTRY = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'ADDRESS_COUNTRY' field has been set */
    public boolean hasADDRESSCOUNTRY() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'ADDRESS_COUNTRY' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder clearADDRESSCOUNTRY() {
      ADDRESS_COUNTRY = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'ADDRESS_POSTCODE' field */
    public java.lang.CharSequence getADDRESSPOSTCODE() {
      return ADDRESS_POSTCODE;
    }
    
    /** Sets the value of the 'ADDRESS_POSTCODE' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder setADDRESSPOSTCODE(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.ADDRESS_POSTCODE = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'ADDRESS_POSTCODE' field has been set */
    public boolean hasADDRESSPOSTCODE() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'ADDRESS_POSTCODE' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder clearADDRESSPOSTCODE() {
      ADDRESS_POSTCODE = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'ADDRESS_CARE_OF' field */
    public java.lang.CharSequence getADDRESSCAREOF() {
      return ADDRESS_CARE_OF;
    }
    
    /** Sets the value of the 'ADDRESS_CARE_OF' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder setADDRESSCAREOF(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.ADDRESS_CARE_OF = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'ADDRESS_CARE_OF' field has been set */
    public boolean hasADDRESSCAREOF() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'ADDRESS_CARE_OF' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder clearADDRESSCAREOF() {
      ADDRESS_CARE_OF = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'ADDRESS_SUPPLIED_COMPANY_NAME' field */
    public java.lang.CharSequence getADDRESSSUPPLIEDCOMPANYNAME() {
      return ADDRESS_SUPPLIED_COMPANY_NAME;
    }
    
    /** Sets the value of the 'ADDRESS_SUPPLIED_COMPANY_NAME' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder setADDRESSSUPPLIEDCOMPANYNAME(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.ADDRESS_SUPPLIED_COMPANY_NAME = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'ADDRESS_SUPPLIED_COMPANY_NAME' field has been set */
    public boolean hasADDRESSSUPPLIEDCOMPANYNAME() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'ADDRESS_SUPPLIED_COMPANY_NAME' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder clearADDRESSSUPPLIEDCOMPANYNAME() {
      ADDRESS_SUPPLIED_COMPANY_NAME = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'ADDRESS_PO_BOX' field */
    public java.lang.CharSequence getADDRESSPOBOX() {
      return ADDRESS_PO_BOX;
    }
    
    /** Sets the value of the 'ADDRESS_PO_BOX' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder setADDRESSPOBOX(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.ADDRESS_PO_BOX = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'ADDRESS_PO_BOX' field has been set */
    public boolean hasADDRESSPOBOX() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'ADDRESS_PO_BOX' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.history.standardisedfields.StandardisedFields.Builder clearADDRESSPOBOX() {
      ADDRESS_PO_BOX = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    public StandardisedFields build() {
      try {
        StandardisedFields record = new StandardisedFields();
        record.COMPANY_NAME = fieldSetFlags()[0] ? this.COMPANY_NAME : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.PROCESSING_DATE = fieldSetFlags()[1] ? this.PROCESSING_DATE : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.ADDRESS_HOUSE_NUMBER = fieldSetFlags()[2] ? this.ADDRESS_HOUSE_NUMBER : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.ADDRESS_STREET = fieldSetFlags()[3] ? this.ADDRESS_STREET : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.ADDRESS_AREA = fieldSetFlags()[4] ? this.ADDRESS_AREA : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.ADDRESS_POST_TOWN = fieldSetFlags()[5] ? this.ADDRESS_POST_TOWN : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.ADDRESS_REGION = fieldSetFlags()[6] ? this.ADDRESS_REGION : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.ADDRESS_COUNTRY = fieldSetFlags()[7] ? this.ADDRESS_COUNTRY : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.ADDRESS_POSTCODE = fieldSetFlags()[8] ? this.ADDRESS_POSTCODE : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.ADDRESS_CARE_OF = fieldSetFlags()[9] ? this.ADDRESS_CARE_OF : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.ADDRESS_SUPPLIED_COMPANY_NAME = fieldSetFlags()[10] ? this.ADDRESS_SUPPLIED_COMPANY_NAME : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.ADDRESS_PO_BOX = fieldSetFlags()[11] ? this.ADDRESS_PO_BOX : (java.lang.CharSequence) defaultValue(fields()[11]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
