/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.header;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class HeaderFields extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"HeaderFields\",\"namespace\":\"com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.header\",\"fields\":[{\"name\":\"SUPPLIED_DATE\",\"type\":[\"null\",\"string\"],\"default\":null,\"dataClassification\":\"3\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence SUPPLIED_DATE;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public HeaderFields() {}

  /**
   * All-args constructor.
   */
  public HeaderFields(java.lang.CharSequence SUPPLIED_DATE) {
    this.SUPPLIED_DATE = SUPPLIED_DATE;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return SUPPLIED_DATE;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: SUPPLIED_DATE = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'SUPPLIED_DATE' field.
   */
  public java.lang.CharSequence getSUPPLIEDDATE() {
    return SUPPLIED_DATE;
  }

  /**
   * Sets the value of the 'SUPPLIED_DATE' field.
   * @param value the value to set.
   */
  public void setSUPPLIEDDATE(java.lang.CharSequence value) {
    this.SUPPLIED_DATE = value;
  }

  /** Creates a new HeaderFields RecordBuilder */
  public static com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.header.HeaderFields.Builder newBuilder() {
    return new com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.header.HeaderFields.Builder();
  }
  
  /** Creates a new HeaderFields RecordBuilder by copying an existing Builder */
  public static com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.header.HeaderFields.Builder newBuilder(com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.header.HeaderFields.Builder other) {
    return new com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.header.HeaderFields.Builder(other);
  }
  
  /** Creates a new HeaderFields RecordBuilder by copying an existing HeaderFields instance */
  public static com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.header.HeaderFields.Builder newBuilder(com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.header.HeaderFields other) {
    return new com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.header.HeaderFields.Builder(other);
  }
  
  /**
   * RecordBuilder for HeaderFields instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<HeaderFields>
    implements org.apache.avro.data.RecordBuilder<HeaderFields> {

    private java.lang.CharSequence SUPPLIED_DATE;

    /** Creates a new Builder */
    private Builder() {
      super(com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.header.HeaderFields.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.header.HeaderFields.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.SUPPLIED_DATE)) {
        this.SUPPLIED_DATE = data().deepCopy(fields()[0].schema(), other.SUPPLIED_DATE);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing HeaderFields instance */
    private Builder(com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.header.HeaderFields other) {
            super(com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.header.HeaderFields.SCHEMA$);
      if (isValidValue(fields()[0], other.SUPPLIED_DATE)) {
        this.SUPPLIED_DATE = data().deepCopy(fields()[0].schema(), other.SUPPLIED_DATE);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'SUPPLIED_DATE' field */
    public java.lang.CharSequence getSUPPLIEDDATE() {
      return SUPPLIED_DATE;
    }
    
    /** Sets the value of the 'SUPPLIED_DATE' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.header.HeaderFields.Builder setSUPPLIEDDATE(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.SUPPLIED_DATE = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'SUPPLIED_DATE' field has been set */
    public boolean hasSUPPLIEDDATE() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'SUPPLIED_DATE' field */
    public com.equifax.fabric.uk.purposing.companies.companyregisterlegacy.header.HeaderFields.Builder clearSUPPLIEDDATE() {
      SUPPLIED_DATE = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public HeaderFields build() {
      try {
        HeaderFields record = new HeaderFields();
        record.SUPPLIED_DATE = fieldSetFlags()[0] ? this.SUPPLIED_DATE : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
